"""phase2 insight: profile, followups, chart_spec

Revision ID: 3e02407d6e1f
Revises: 6e317c803594
Create Date: 2026-07-03 12:53:13.111548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e02407d6e1f'
down_revision: Union[str, None] = '6e317c803594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('chart_spec_json', sa.Text(), nullable=True))
    op.add_column('datasets', sa.Column('profile_json', sa.Text(), nullable=True))
    op.add_column('datasets', sa.Column('followups_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'followups_json')
    op.drop_column('datasets', 'profile_json')
    op.drop_column('analysis_runs', 'chart_spec_json')
    # ### end Alembic commands ###
